# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 105b98e1c300831bbea9be21979be99b1382a99e425c241671895293a0d502ce1bf317128914305f6a62446b4482e28b1315fc5af11e02cc9225a50d6d784fcd

test:
  secret_key_base: 930e7ce22a84bb3f131463d325b8c0fadeefc9310d5d8b9289e6d1aaaa62d13e5d55a67459e446083f6b47597ba9cd35bf062ac0feaaabed9adbe4573c2a3be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
